name: Test STT (Whisper)

on:
  workflow_dispatch:

jobs:
  transcribe:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install System Dependencies
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Install Whisper
      run: pip install git+https://github.com/openai/whisper.git

    - name: Run Transcription Script
      run: python transcribe.py
